import "./globals.css";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// // }) {
// //   return (
// //     <html lang="en">
// //       <body>{children}</body>
// //     </html>
// //   )
// // }

// import "@/app/globals.css";
// import { AddressBar } from '#/ui/address-bar';
// import Byline from '#/ui/byline';
// import { GlobalNav } from '#/ui/global-nav';
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Fugoku",
    template: "%s | FE",
  },
  description: "Fugoku",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="[color-scheme:light]">
      <body>{children}</body>
    </html>
  );
}
